name: Create Release

on:
  push:
    branches:
    - master

jobs:
  unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run Unit Tests
      run: go test -v -count=1 ./...

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: unit
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    - name: Tag
      id: tag
      uses: paketo-buildpacks/github-config/actions/tag@master
    - name: Create Release
      id: create-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.tag.outputs.tag }}
        release_name: v${{ steps.tag.outputs.tag }}
        draft: false
        prerelease: false
